"""empty message

Revision ID: 4290779a2f7d
Revises: None
Create Date: 2014-11-12 16:46:20.383919

"""

# revision identifiers, used by Alembic.
revision = '4290779a2f7d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
